/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_libavndkdemo_Videokit */

#ifndef _Included_com_example_libavndkdemo_Videokit
#define _Included_com_example_libavndkdemo_Videokit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_libavndkdemo_Videokit
 * Method:    run
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_libavndkdemo_Videokit_run
  (JNIEnv *, jobject, jobjectArray);

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *jvm, void *reserved);

#ifdef __cplusplus
}
#endif
#endif
